//! Local rule-file rendering only: these functions neither install nor evaluate alerts.
const std = @import("std");
const policy = @import("policy.zig");
const parse = @import("../cli/parse.zig");

const header = "# Generated by DragonTools; rule generation only, not deployed.\n";
// Ignore pseudo/temporary filesystems and immutable images. Check capacity and
// read-only status separately so a zero-size or read-only mount cannot alert.
const filesystem_selector = "{fstype!~\"autofs|binfmt_misc|bpf|cgroup2?|configfs|debugfs|devpts|devtmpfs|efivarfs|fusectl|hugetlbfs|mqueue|nsfs|overlay|proc|pstore|ramfs|rootfs|rpc_pipefs|securityfs|selinuxfs|squashfs|sysfs|tmpfs|tracefs\"}";

/// The caller owns the returned YAML. HostDown covers configured scrape targets;
/// the remaining rules require node_exporter metrics with an instance label.
pub fn renderHosts(a: std.mem.Allocator) ![]const u8 {
    var out: std.Io.Writer.Allocating = .init(a);
    errdefer out.deinit();
    const w = &out.writer;
    try w.writeAll(header ++ "groups:\n  - name: dragontools-hosts\n    type: prometheus\n    rules:\n");

    try beginRule(w, "HostDown");
    try w.writeAll("up == 0\n");
    try finishRule(w, policy.host.down_for, "critical", "prometheus", null, "Scrape target {{ $labels.instance }} is unavailable", "Scraping has failed; up={{ $value }}.");

    try beginRule(w, "CPUHigh");
    // The complement of idle CPU measures non-idle time without double-counting
    // guest CPU counters. Retain job/instance/host across the per-CPU average.
    try w.print("100 * (1 - avg by (job, instance, host) (rate(node_cpu_seconds_total{{mode=\"idle\"}}[{s}]))) > {d}\n", .{
        policy.host.cpu_rate_window,
        policy.host.cpu_percent,
    });
    try finishRule(w, policy.host.cpu_for, "warning", "node_exporter", null, "High CPU usage on {{ $labels.instance }}", "Non-idle CPU usage is {{ $value }}%.");

    try beginRule(w, "MemoryPressure");
    try w.print("(100 * (1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) > {d}) and (node_memory_MemTotal_bytes > 0)\n", .{policy.host.memory_percent});
    try finishRule(w, policy.host.memory_for, "warning", "node_exporter", null, "Memory pressure on {{ $labels.instance }}", "Memory usage excluding available memory is {{ $value }}%.");

    try diskRule(w, "DiskWarning", policy.disk.warning_percent, "warning");
    try diskRule(w, "DiskCritical", policy.disk.critical_percent, "critical");

    try beginRule(w, "InodesCritical");
    try w.print("(100 * (1 - node_filesystem_files_free{s} / node_filesystem_files{s}) >= {d}) and (node_filesystem_files{s} > 0) and (node_filesystem_readonly{s} == 0)\n", .{
        filesystem_selector,
        filesystem_selector,
        policy.host.inode_percent,
        filesystem_selector,
        filesystem_selector,
    });
    try finishRule(w, policy.host.inode_for, "critical", "node_exporter", null, "Inode pressure on {{ $labels.instance }} at {{ $labels.mountpoint }}", "Filesystem inode usage is {{ $value }}%.");
    return out.toOwnedSlice();
}

fn diskRule(w: *std.Io.Writer, name: []const u8, threshold: u8, severity: []const u8) !void {
    try beginRule(w, name);
    try w.print("(100 * (1 - node_filesystem_avail_bytes{s} / node_filesystem_size_bytes{s}) >= {d}) and (node_filesystem_size_bytes{s} > 0) and (node_filesystem_readonly{s} == 0)\n", .{
        filesystem_selector,
        filesystem_selector,
        threshold,
        filesystem_selector,
        filesystem_selector,
    });
    try finishRule(w, policy.host.disk_for, severity, "node_exporter", null, "Disk pressure on {{ $labels.instance }} at {{ $labels.mountpoint }}", "Filesystem usage including reserved space is {{ $value }}%.");
}

/// Render only explicitly selected services, in sorted order without duplicates.
/// Future agents MUST enable --collector.systemd and
/// --collector.systemd.enable-restarts-metrics, include every selected unit, and
/// verify both metrics are present. The restart counter comes from NRestarts
/// (systemd >=235); it counts automatic Restart triggers, not all manual starts.
/// Source: https://github.com/prometheus/node_exporter/blob/master/collector/systemd_linux.go
/// Missing/unloaded units or missing collectors do not yield a ServiceDown series;
/// collector coverage and absent-series monitoring remain integration gates.
pub fn renderServices(a: std.mem.Allocator, services: []const []const u8) ![]const u8 {
    for (services) |service| try parse.validateValue("--service", service);
    const ordered = try a.dupe([]const u8, services);
    defer a.free(ordered);
    std.mem.sort([]const u8, ordered, {}, serviceLessThan);

    var out: std.Io.Writer.Allocating = .init(a);
    errdefer out.deinit();
    const w = &out.writer;
    try w.writeAll(header);
    if (ordered.len == 0) {
        try w.writeAll("groups: []\n");
        return out.toOwnedSlice();
    }
    try w.writeAll("groups:\n  - name: dragontools-services\n    type: prometheus\n    rules:\n");
    for (ordered, 0..) |service, i| {
        if (i > 0 and std.mem.eql(u8, service, ordered[i - 1])) continue;
        try beginRule(w, "ServiceDown");
        try w.writeAll("node_systemd_unit_state{name=");
        try promString(w, service);
        try w.writeAll(",state=\"active\"} == 0\n");
        try finishRule(w, policy.service.down_for, "critical", "node_exporter", service, "Service {{ $labels.service }} is not active on {{ $labels.instance }}", "The selected systemd unit has active-state signal {{ $value }}.");

        try beginRule(w, "ServiceRestartLoop");
        try w.writeAll("increase(node_systemd_service_restart_total{name=");
        try promString(w, service);
        try w.print("}}[{s}]) >= {d}\n", .{
            policy.service.restart_window,
            policy.service.restart_count,
        });
        try finishRule(w, policy.service.restart_for, "warning", "node_exporter", service, "Service {{ $labels.service }} is restarting repeatedly on {{ $labels.instance }}", "Automatic systemd restarts in the evaluation window: {{ $value }}.");
    }
    return out.toOwnedSlice();
}

fn serviceLessThan(_: void, left: []const u8, right: []const u8) bool {
    return std.mem.lessThan(u8, left, right);
}

/// Separate file for a VictoriaLogs datasource, never a PromQL-only evaluator.
/// Upstream requires type:vlogs and stats followed by a threshold filter:
/// https://docs.victoriametrics.com/victorialogs/vmalert/
/// Explicit _time windows avoid inheriting the group's shorter interval; upstream
/// currently does not support replay/backfill with custom time filters. No `for`
/// means firing at the first matching evaluation, not instantaneous delivery.
/// https://docs.victoriametrics.com/victorialogs/logsql/#multi-exact-filter
/// in(...) matches exact normalized levels, never words in unstructured messages.
/// Only service/count survive aggregation. Missing service becomes one unnamed
/// group; a future ingestion path must normalize service and bound its cardinality.
pub fn renderLogs(a: std.mem.Allocator) ![]const u8 {
    var out: std.Io.Writer.Allocating = .init(a);
    errdefer out.deinit();
    const w = &out.writer;
    try w.writeAll(header ++ "groups:\n  - name: dragontools-logs\n    type: vlogs\n");
    try w.print("    interval: {s}\n    rules:\n", .{policy.log_alerts.evaluation_interval});

    try beginRule(w, "ErrorBurst");
    try w.print("_time:{s} level:in(error) | stats by (service) count() as errors | filter errors:>={d}\n", .{
        policy.log_alerts.error_window,
        policy.log_alerts.error_count,
    });
    try finishRule(w, null, "warning", "victorialogs", null, "Error burst from service {{ $labels.service }}", "Structured error events in the evaluation window: {{ $value }}.");

    try beginRule(w, "CriticalLogEvent");
    try w.print("_time:{s} level:in(critical,fatal) | stats by (service) count() as events | filter events:>={d}\n", .{
        policy.log_alerts.critical_window,
        policy.log_alerts.critical_count,
    });
    try finishRule(w, null, "critical", "victorialogs", null, "Critical or fatal event from service {{ $labels.service }}", "Structured critical or fatal events in the evaluation window: {{ $value }}.");
    return out.toOwnedSlice();
}

fn beginRule(w: *std.Io.Writer, name: []const u8) !void {
    try w.print("      - alert: {s}\n        expr: >-\n          ", .{name});
}

fn finishRule(w: *std.Io.Writer, duration: ?[]const u8, severity: []const u8, source: []const u8, service: ?[]const u8, summary: []const u8, description: []const u8) !void {
    if (duration) |value| try w.print("        for: {s}\n", .{value});
    try w.writeAll("        labels:\n          severity: ");
    try yamlString(w, severity);
    try w.writeAll("\n          source: ");
    try yamlString(w, source);
    if (service) |value| {
        try w.writeAll("\n          service: ");
        try yamlString(w, value);
    }
    try w.writeAll("\n        annotations:\n          summary: ");
    try yamlString(w, summary);
    try w.writeAll("\n          description: ");
    try yamlString(w, description);
    try w.writeByte('\n');
}

// YAML single-quoted strings keep colon, @, braces and backslash literal.
// Callers provide validated service names or constant single-line text.
fn yamlString(w: *std.Io.Writer, value: []const u8) !void {
    try w.writeByte('\'');
    for (value) |c| {
        if (c == '\'') try w.writeByte('\'');
        try w.writeByte(c);
    }
    try w.writeByte('\'');
}

// Exact matchers avoid treating dots or other unit-name punctuation as regex.
// The shared validator currently excludes quotes, slashes and control bytes.
fn promString(w: *std.Io.Writer, value: []const u8) !void {
    try w.writeByte('"');
    for (value) |c| {
        if (c == '"' or c == '\\') try w.writeByte('\\');
        try w.writeByte(c);
    }
    try w.writeByte('"');
}

fn expectContains(haystack: []const u8, needle: []const u8) !void {
    try std.testing.expect(std.mem.indexOf(u8, haystack, needle) != null);
}

fn ruleBlock(yaml: []const u8, name: []const u8) ![]const u8 {
    const start = std.mem.indexOf(u8, yaml, name) orelse return error.MissingRule;
    const end = std.mem.indexOf(u8, yaml[start..], "      - alert:") orelse yaml.len - start;
    return yaml[start .. start + end];
}

test "host rules are deterministic and carry stable labels and annotations" {
    const a = std.testing.allocator;
    const first = try renderHosts(a);
    defer a.free(first);
    const second = try renderHosts(a);
    defer a.free(second);
    try std.testing.expectEqualStrings(first, second);
    try expectContains(first, "type: prometheus\n");
    try std.testing.expectEqual(@as(usize, 6), std.mem.count(u8, first, "      - alert: "));
    for ([_][]const u8{ "HostDown", "CPUHigh", "MemoryPressure", "DiskWarning", "DiskCritical", "InodesCritical" }) |name| {
        const block = try ruleBlock(first, name);
        try expectContains(block, "        labels:\n          severity: '");
        try expectContains(block, "          source: '");
        try expectContains(block, "        annotations:\n          summary: '");
        try expectContains(block, "{{ $labels.instance }}");
        try expectContains(block, "{{ $value }}");
    }
    const down = try ruleBlock(first, "HostDown");
    try expectContains(down, "up == 0\n        for: 2m\n");
    try expectContains(down, "severity: 'critical'");
}

test "CPU and memory rules use policy thresholds and sustained signals" {
    const a = std.testing.allocator;
    const yaml = try renderHosts(a);
    defer a.free(yaml);
    const cpu = try ruleBlock(yaml, "CPUHigh");
    try expectContains(cpu, "100 * (1 - avg by (job, instance, host) (rate(node_cpu_seconds_total{mode=\"idle\"}[5m]))) > 90\n        for: 10m\n");
    try std.testing.expect(std.mem.indexOf(u8, cpu, "node_load") == null);
    const memory = try ruleBlock(yaml, "MemoryPressure");
    try expectContains(memory, "node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) > 90)");
    try expectContains(memory, "node_memory_MemTotal_bytes > 0");
    try expectContains(memory, "for: 5m\n");
    try std.testing.expect(std.mem.indexOf(u8, memory, "MemFree") == null);
}

test "disk and inode thresholds exclude inappropriate filesystems and zero capacity" {
    const a = std.testing.allocator;
    const yaml = try renderHosts(a);
    defer a.free(yaml);
    for ([_][]const u8{ "DiskWarning", "DiskCritical", "InodesCritical" }, [_][]const u8{ ") >= 70)", ") >= 80)", ") >= 90)" }) |name, threshold| {
        const block = try ruleBlock(yaml, name);
        try expectContains(block, threshold);
        try expectContains(block, "fstype!~\"");
        try expectContains(block, "tmpfs");
        try expectContains(block, "proc");
        try expectContains(block, "} > 0)");
        try expectContains(block, "node_filesystem_readonly");
        try expectContains(block, "for: 5m\n");
    }
    try expectContains(try ruleBlock(yaml, "DiskWarning"), "severity: 'warning'");
    try expectContains(try ruleBlock(yaml, "DiskCritical"), "severity: 'critical'");
    try expectContains(try ruleBlock(yaml, "InodesCritical"), "node_filesystem_files_free");
}

test "one selected service has exact state and explicitly planned restart metrics" {
    const a = std.testing.allocator;
    const yaml = try renderServices(a, &.{"orderflow.service"});
    defer a.free(yaml);
    try std.testing.expectEqual(@as(usize, 2), std.mem.count(u8, yaml, "      - alert: "));
    try expectContains(yaml, "node_systemd_unit_state{name=\"orderflow.service\",state=\"active\"} == 0\n        for: 2m\n");
    try expectContains(yaml, "increase(node_systemd_service_restart_total{name=\"orderflow.service\"}[5m]) >= 3\n        for: 1m\n");
    try std.testing.expectEqual(@as(usize, 2), std.mem.count(u8, yaml, "service: 'orderflow.service'"));
    try std.testing.expect(std.mem.indexOf(u8, yaml, "name=~") == null);
    try std.testing.expect(std.mem.indexOf(u8, yaml, "whoami.service") == null);
    try expectContains(yaml, "source: 'node_exporter'");
}

test "service rules are canonical across input order and duplicates without mutating input" {
    const a = std.testing.allocator;
    var services = [_][]const u8{ "whoami.service", "orderflow.service", "whoami.service" };
    const yaml = try renderServices(a, &services);
    defer a.free(yaml);
    const sorted = try renderServices(a, &.{ "orderflow.service", "whoami.service" });
    defer a.free(sorted);
    try std.testing.expectEqualStrings(sorted, yaml);
    try std.testing.expectEqualStrings("whoami.service", services[0]);
    try std.testing.expectEqual(@as(usize, 2), std.mem.count(u8, yaml, "- alert: ServiceDown\n"));
    try std.testing.expectEqual(@as(usize, 2), std.mem.count(u8, yaml, "- alert: ServiceRestartLoop\n"));
}

test "empty service selection renders a valid empty group list" {
    const a = std.testing.allocator;
    const yaml = try renderServices(a, &.{});
    defer a.free(yaml);
    try std.testing.expectEqualStrings(header ++ "groups: []\n", yaml);
    try std.testing.expect(std.mem.indexOf(u8, yaml, "Service") == null);
}

test "validated unit punctuation stays literal in YAML and exact PromQL selectors" {
    const a = std.testing.allocator;
    const yaml = try renderServices(a, &.{"worker_queue@east:1-2.service"});
    defer a.free(yaml);
    try expectContains(yaml, "service: 'worker_queue@east:1-2.service'");
    try expectContains(yaml, "name=\"worker_queue@east:1-2.service\"");
    for ([_][]const u8{ "bad'unit.service", "bad\"unit.service", "bad\\unit.service", "bad\nunit.service", "bad unit.service", "x.*.service", "../x.service", "$(id).service", "x.timer" }) |invalid| {
        try std.testing.expectError(error.InvalidService, renderServices(a, &.{ "valid.service", invalid }));
    }
    var quoted: std.Io.Writer.Allocating = .init(a);
    defer quoted.deinit();
    try yamlString(&quoted.writer, "worker's state: {{ $value }}");
    try std.testing.expectEqualStrings("'worker''s state: {{ $value }}'", quoted.written());
}

test "VictoriaLogs rules use exact severity stats filtering and explicit rolling windows" {
    const a = std.testing.allocator;
    const first = try renderLogs(a);
    defer a.free(first);
    const second = try renderLogs(a);
    defer a.free(second);
    try std.testing.expectEqualStrings(first, second);
    try expectContains(first, "type: vlogs\n    interval: 1m\n");
    try std.testing.expectEqual(@as(usize, 2), std.mem.count(u8, first, "      - alert: "));
    const errors = try ruleBlock(first, "ErrorBurst");
    try expectContains(errors, "_time:5m level:in(error) | stats by (service) count() as errors | filter errors:>=5\n");
    try expectContains(errors, "severity: 'warning'");
    const critical = try ruleBlock(first, "CriticalLogEvent");
    try expectContains(critical, "_time:1m level:in(critical,fatal) | stats by (service) count() as events | filter events:>=1\n");
    try expectContains(critical, "severity: 'critical'");
    try std.testing.expectEqual(@as(usize, 2), std.mem.count(u8, first, "source: 'victorialogs'"));
    try std.testing.expect(std.mem.indexOf(u8, first, "        for:") == null);
    for ([_][]const u8{ "_msg", "row_any", "request_id", "duration_ms", "{{ query" }) |sensitive| {
        try std.testing.expect(std.mem.indexOf(u8, first, sensitive) == null);
    }
    for ([_][]const u8{ errors, critical }) |block| {
        try expectContains(block, "{{ $labels.service }}");
        try expectContains(block, "{{ $value }}");
    }
}
