//! Local rule-file rendering only: these functions neither install nor evaluate alerts.
const std = @import("std");
const policy = @import("policy.zig");
const parse = @import("../cli/parse.zig");

const header = "# Generated by DragonTools; provisional local rules, not deployed.\n";

/// Activated only for the real agent slice. Names/labels were observed from the
/// pinned Vector Linux fixture and are constrained to agent="vector" identities.
pub fn renderHosts(a: std.mem.Allocator) ![]const u8 {
    const metrics = @import("agents/metric_contract.zig");
    var out: std.Io.Writer.Allocating = .init(a);
    errdefer out.deinit();
    const w = &out.writer;
    try w.writeAll("# Managed by DragonTools; verified Vector host metric contract\ngroups:\n  - name: dragontools-hosts\n    interval: 30s\n    rules:\n");
    try beginRule(w, "CPUHigh");
    try w.print("100 * (1 - avg by (application, environment, host) (rate({s}{{agent=\"vector\",mode=\"idle\"}}[{s}]))) > {d}\n", .{ metrics.cpu, policy.host.cpu_rate_window, policy.host.cpu_percent });
    try finishRule(w, policy.host.cpu_for, "warning", "vector", null, "High CPU on {{ $labels.host }}", "CPU utilization is above the managed host threshold.");
    try beginRule(w, "MemoryPressure");
    try w.print("100 * (1 - {s}{{agent=\"vector\"}} / {s}{{agent=\"vector\"}}) > {d}\n", .{ metrics.memory_available, metrics.memory_total, policy.host.memory_percent });
    try finishRule(w, policy.host.memory_for, "warning", "vector", null, "Memory pressure on {{ $labels.host }}", "Available host memory is below the managed threshold.");
    try beginRule(w, "DiskWarning");
    try w.print("100 * {s}{{agent=\"vector\"}} >= {d}\n", .{ metrics.filesystem_ratio, policy.disk.warning_percent });
    try finishRule(w, policy.host.disk_for, "warning", "vector", null, "Disk warning on {{ $labels.host }}", "Filesystem {{ $labels.mountpoint }} is above the warning threshold.");
    try beginRule(w, "DiskCritical");
    try w.print("100 * {s}{{agent=\"vector\"}} >= {d}\n", .{ metrics.filesystem_ratio, policy.disk.critical_percent });
    try finishRule(w, policy.host.disk_for, "critical", "vector", null, "Disk critical on {{ $labels.host }}", "Filesystem {{ $labels.mountpoint }} is above the critical threshold.");
    try beginRule(w, "InodesCritical");
    try w.print("(100 * {s}{{agent=\"vector\"}} >= {d}) and ({s}{{agent=\"vector\"}} > 0)\n", .{ metrics.inode_ratio, policy.host.inode_percent, metrics.inode_total });
    try finishRule(w, policy.host.inode_for, "critical", "vector", null, "Inodes critical on {{ $labels.host }}", "Filesystem {{ $labels.mountpoint }} is above the inode threshold.");
    try beginRule(w, "SecurityUpdatesPending");
    try w.writeAll("dragontool_host_security_updates_pending{agent=\"vector\"} > 0\n");
    try finishRule(w, "24h", "warning", "vector", null, "Security updates pending on {{ $labels.host }}", "Ubuntu reports pending security updates for at least 24 hours; review the host maintenance state.");
    try beginRule(w, "RebootRequired");
    try w.writeAll("dragontool_host_reboot_required{agent=\"vector\"} == 1\n");
    try finishRule(w, "24h", "warning", "vector", null, "Reboot required on {{ $labels.host }}", "Ubuntu has requested a reboot for at least 24 hours; schedule maintenance.");
    return out.toOwnedSlice();
}

/// The systemd service-state/restart metric contract is intentionally deferred.
/// Validate selections as usual, then refuse to emit unusable alert expressions.
pub fn renderServices(a: std.mem.Allocator, services: []const []const u8) ![]const u8 {
    for (services) |service| try parse.validateValue("--service", service);
    if (services.len != 0) return error.ServiceMetricContractUnavailable;
    return a.dupe(u8, header ++ "groups: []\n");
}

/// Separate file for a VictoriaLogs datasource, never a PromQL-only evaluator.
/// Upstream requires type:vlogs and stats followed by a threshold filter:
/// https://docs.victoriametrics.com/victorialogs/vmalert/
/// Explicit _time windows avoid inheriting the group's shorter interval; upstream
/// currently does not support replay/backfill with custom time filters. No `for`
/// means firing at the first matching evaluation, not instantaneous delivery.
/// https://docs.victoriametrics.com/victorialogs/logsql/#multi-exact-filter
/// in(...) matches exact normalized levels, never words in unstructured messages.
/// Only service/count survive aggregation. Missing service becomes one unnamed
/// group; a future ingestion path must normalize service and bound its cardinality.
pub fn renderLogs(a: std.mem.Allocator) ![]const u8 {
    var out: std.Io.Writer.Allocating = .init(a);
    errdefer out.deinit();
    const w = &out.writer;
    try w.writeAll(header ++ "groups:\n  - name: dragontools-logs\n    type: vlogs\n");
    try w.print("    interval: {s}\n    rules:\n", .{policy.log_alerts.evaluation_interval});

    try beginRule(w, "ErrorBurst");
    try w.print("_time:{s} level:in(error) | stats by (application, environment, host, service) count() as errors | filter errors:>={d}\n", .{
        policy.log_alerts.error_window,
        policy.log_alerts.error_count,
    });
    try finishRule(w, null, "warning", "victorialogs", null, "Error burst from service {{ $labels.service }}", "Structured error events in the evaluation window: {{ $value }}.");

    try beginRule(w, "CriticalLogEvent");
    try w.print("_time:{s} level:in(critical,fatal) | stats by (application, environment, host, service) count() as events | filter events:>={d}\n", .{
        policy.log_alerts.critical_window,
        policy.log_alerts.critical_count,
    });
    try finishRule(w, null, "critical", "victorialogs", null, "Critical or fatal event from service {{ $labels.service }}", "Structured critical or fatal events in the evaluation window: {{ $value }}.");
    return out.toOwnedSlice();
}

fn beginRule(w: *std.Io.Writer, name: []const u8) !void {
    try w.print("      - alert: {s}\n        expr: >-\n          ", .{name});
}

fn finishRule(w: *std.Io.Writer, duration: ?[]const u8, severity: []const u8, source: []const u8, service: ?[]const u8, summary: []const u8, description: []const u8) !void {
    if (duration) |value| try w.print("        for: {s}\n", .{value});
    try w.writeAll("        labels:\n          managed_by: dragontools\n          severity: ");
    try yamlString(w, severity);
    try w.writeAll("\n          source: ");
    try yamlString(w, source);
    if (service) |value| {
        try w.writeAll("\n          service: ");
        try yamlString(w, value);
    }
    try w.writeAll("\n        annotations:\n          summary: ");
    try yamlString(w, summary);
    try w.writeAll("\n          description: ");
    try yamlString(w, description);
    try w.writeByte('\n');
}

// YAML single-quoted strings keep colon, @, braces and backslash literal.
// Callers provide validated service names or constant single-line text.
fn yamlString(w: *std.Io.Writer, value: []const u8) !void {
    try w.writeByte('\'');
    for (value) |c| {
        if (c == '\'') try w.writeByte('\'');
        try w.writeByte(c);
    }
    try w.writeByte('\'');
}

fn expectContains(haystack: []const u8, needle: []const u8) !void {
    try std.testing.expect(std.mem.indexOf(u8, haystack, needle) != null);
}

fn ruleBlock(yaml: []const u8, name: []const u8) ![]const u8 {
    const start = std.mem.indexOf(u8, yaml, name) orelse return error.MissingRule;
    const end = std.mem.indexOf(u8, yaml[start..], "      - alert:") orelse yaml.len - start;
    return yaml[start .. start + end];
}

test "selected-service rendering fails until its metric contract is established" {
    const a = std.testing.allocator;
    try std.testing.expectError(error.ServiceMetricContractUnavailable, renderServices(a, &.{"orderflow.service"}));
    try std.testing.expectError(error.ServiceMetricContractUnavailable, renderServices(a, &.{ "worker_queue@east:1-2.service", "whoami.service" }));
    for ([_][]const u8{ "bad'unit.service", "bad\"unit.service", "bad\\unit.service", "bad\nunit.service", "bad unit.service", "x.*.service", "../x.service", "$(id).service", "x.timer" }) |invalid| {
        try std.testing.expectError(error.InvalidService, renderServices(a, &.{ "valid.service", invalid }));
    }
}

test "empty service selection remains an explicit empty group list" {
    const a = std.testing.allocator;
    const yaml = try renderServices(a, &.{});
    defer a.free(yaml);
    try std.testing.expectEqualStrings(header ++ "groups: []\n", yaml);
}

test "VictoriaLogs rules use exact severity stats filtering and explicit rolling windows" {
    const a = std.testing.allocator;
    const first = try renderLogs(a);
    defer a.free(first);
    const second = try renderLogs(a);
    defer a.free(second);
    try std.testing.expectEqualStrings(first, second);
    try expectContains(first, "type: vlogs\n    interval: 1m\n");
    try std.testing.expectEqual(@as(usize, 2), std.mem.count(u8, first, "      - alert: "));
    const errors = try ruleBlock(first, "ErrorBurst");
    try expectContains(errors, "_time:5m level:in(error) | stats by (application, environment, host, service) count() as errors | filter errors:>=5\n");
    try expectContains(errors, "severity: 'warning'");
    const critical = try ruleBlock(first, "CriticalLogEvent");
    try expectContains(critical, "_time:1m level:in(critical,fatal) | stats by (application, environment, host, service) count() as events | filter events:>=1\n");
    try expectContains(critical, "severity: 'critical'");
    try std.testing.expectEqual(@as(usize, 2), std.mem.count(u8, first, "source: 'victorialogs'"));
    try std.testing.expect(std.mem.indexOf(u8, first, "        for:") == null);
    for ([_][]const u8{ "_msg", "row_any", "request_id", "duration_ms", "{{ query" }) |sensitive| {
        try std.testing.expect(std.mem.indexOf(u8, first, sensitive) == null);
    }
    for ([_][]const u8{ errors, critical }) |block| {
        try expectContains(block, "{{ $labels.service }}");
        try expectContains(block, "{{ $value }}");
    }
}

test "host alerts use the verified Vector contract and policy thresholds" {
    const a = std.testing.allocator;
    const rendered = try renderHosts(a);
    defer a.free(rendered);
    for ([_][]const u8{ "CPUHigh", "MemoryPressure", "DiskWarning", "DiskCritical", "InodesCritical", "host_cpu_seconds_total", "host_memory_available_bytes", "host_memory_total_bytes", "host_filesystem_used_ratio", "host_filesystem_inodes_used_ratio", "host_filesystem_inodes_total", "agent=\"vector\"", "for: 10m", "for: 5m", "> 90", ">= 70", ">= 80", ">= 90" }) |needle| try expectContains(rendered, needle);
    try std.testing.expect(std.mem.indexOf(u8, rendered, "ServiceDown") == null);
    try std.testing.expect(std.mem.indexOf(u8, rendered, "node_") == null);
}

test "maintenance warnings use observed names and wait 24 hours without general update alert" {
    const output = try renderHosts(std.testing.allocator);
    defer std.testing.allocator.free(output);
    const observed = @embedFile("agents/maintenance_fixture.prom");
    for ([_][]const u8{ "SecurityUpdatesPending", "RebootRequired" }, [_][]const u8{ "dragontool_host_security_updates_pending", "dragontool_host_reboot_required" }) |name, metric| {
        try expectContains(observed, metric);
        const block = try ruleBlock(output, name);
        try expectContains(block, metric);
        try expectContains(block, "for: 24h");
        try expectContains(block, "severity: 'warning'");
    }
    try std.testing.expect(std.mem.indexOf(u8, output, "dragontool_host_updates_pending") == null);
}
