//! Local rule-file rendering only: these functions neither install nor evaluate alerts.
const std = @import("std");
const policy = @import("policy.zig");
const parse = @import("../cli/parse.zig");

const header = "# Generated by DragonTools; provisional local rules, not deployed.\n";

/// Host alert policy exists, but rendering waits for the Vector agent slice to
/// establish and verify the real metric/label contract. Never invent expressions.
pub fn renderHosts(_: std.mem.Allocator) error{HostMetricContractUnavailable}![]const u8 {
    return error.HostMetricContractUnavailable;
}

/// The systemd service-state/restart metric contract is intentionally deferred.
/// Validate selections as usual, then refuse to emit unusable alert expressions.
pub fn renderServices(a: std.mem.Allocator, services: []const []const u8) ![]const u8 {
    for (services) |service| try parse.validateValue("--service", service);
    if (services.len != 0) return error.ServiceMetricContractUnavailable;
    return a.dupe(u8, header ++ "groups: []\n");
}

/// Separate file for a VictoriaLogs datasource, never a PromQL-only evaluator.
/// Upstream requires type:vlogs and stats followed by a threshold filter:
/// https://docs.victoriametrics.com/victorialogs/vmalert/
/// Explicit _time windows avoid inheriting the group's shorter interval; upstream
/// currently does not support replay/backfill with custom time filters. No `for`
/// means firing at the first matching evaluation, not instantaneous delivery.
/// https://docs.victoriametrics.com/victorialogs/logsql/#multi-exact-filter
/// in(...) matches exact normalized levels, never words in unstructured messages.
/// Only service/count survive aggregation. Missing service becomes one unnamed
/// group; a future ingestion path must normalize service and bound its cardinality.
pub fn renderLogs(a: std.mem.Allocator) ![]const u8 {
    var out: std.Io.Writer.Allocating = .init(a);
    errdefer out.deinit();
    const w = &out.writer;
    try w.writeAll(header ++ "groups:\n  - name: dragontools-logs\n    type: vlogs\n");
    try w.print("    interval: {s}\n    rules:\n", .{policy.log_alerts.evaluation_interval});

    try beginRule(w, "ErrorBurst");
    try w.print("_time:{s} level:in(error) | stats by (service) count() as errors | filter errors:>={d}\n", .{
        policy.log_alerts.error_window,
        policy.log_alerts.error_count,
    });
    try finishRule(w, null, "warning", "victorialogs", null, "Error burst from service {{ $labels.service }}", "Structured error events in the evaluation window: {{ $value }}.");

    try beginRule(w, "CriticalLogEvent");
    try w.print("_time:{s} level:in(critical,fatal) | stats by (service) count() as events | filter events:>={d}\n", .{
        policy.log_alerts.critical_window,
        policy.log_alerts.critical_count,
    });
    try finishRule(w, null, "critical", "victorialogs", null, "Critical or fatal event from service {{ $labels.service }}", "Structured critical or fatal events in the evaluation window: {{ $value }}.");
    return out.toOwnedSlice();
}

fn beginRule(w: *std.Io.Writer, name: []const u8) !void {
    try w.print("      - alert: {s}\n        expr: >-\n          ", .{name});
}

fn finishRule(w: *std.Io.Writer, duration: ?[]const u8, severity: []const u8, source: []const u8, service: ?[]const u8, summary: []const u8, description: []const u8) !void {
    if (duration) |value| try w.print("        for: {s}\n", .{value});
    try w.writeAll("        labels:\n          severity: ");
    try yamlString(w, severity);
    try w.writeAll("\n          source: ");
    try yamlString(w, source);
    if (service) |value| {
        try w.writeAll("\n          service: ");
        try yamlString(w, value);
    }
    try w.writeAll("\n        annotations:\n          summary: ");
    try yamlString(w, summary);
    try w.writeAll("\n          description: ");
    try yamlString(w, description);
    try w.writeByte('\n');
}

// YAML single-quoted strings keep colon, @, braces and backslash literal.
// Callers provide validated service names or constant single-line text.
fn yamlString(w: *std.Io.Writer, value: []const u8) !void {
    try w.writeByte('\'');
    for (value) |c| {
        if (c == '\'') try w.writeByte('\'');
        try w.writeByte(c);
    }
    try w.writeByte('\'');
}

fn expectContains(haystack: []const u8, needle: []const u8) !void {
    try std.testing.expect(std.mem.indexOf(u8, haystack, needle) != null);
}

fn ruleBlock(yaml: []const u8, name: []const u8) ![]const u8 {
    const start = std.mem.indexOf(u8, yaml, name) orelse return error.MissingRule;
    const end = std.mem.indexOf(u8, yaml[start..], "      - alert:") orelse yaml.len - start;
    return yaml[start .. start + end];
}

test "host and selected-service rendering fail until metric contracts are established" {
    const a = std.testing.allocator;
    try std.testing.expectError(error.HostMetricContractUnavailable, renderHosts(a));
    try std.testing.expectError(error.ServiceMetricContractUnavailable, renderServices(a, &.{"orderflow.service"}));
    try std.testing.expectError(error.ServiceMetricContractUnavailable, renderServices(a, &.{ "worker_queue@east:1-2.service", "whoami.service" }));
    for ([_][]const u8{ "bad'unit.service", "bad\"unit.service", "bad\\unit.service", "bad\nunit.service", "bad unit.service", "x.*.service", "../x.service", "$(id).service", "x.timer" }) |invalid| {
        try std.testing.expectError(error.InvalidService, renderServices(a, &.{ "valid.service", invalid }));
    }
}

test "empty service selection remains an explicit empty group list" {
    const a = std.testing.allocator;
    const yaml = try renderServices(a, &.{});
    defer a.free(yaml);
    try std.testing.expectEqualStrings(header ++ "groups: []\n", yaml);
}

test "VictoriaLogs rules use exact severity stats filtering and explicit rolling windows" {
    const a = std.testing.allocator;
    const first = try renderLogs(a);
    defer a.free(first);
    const second = try renderLogs(a);
    defer a.free(second);
    try std.testing.expectEqualStrings(first, second);
    try expectContains(first, "type: vlogs\n    interval: 1m\n");
    try std.testing.expectEqual(@as(usize, 2), std.mem.count(u8, first, "      - alert: "));
    const errors = try ruleBlock(first, "ErrorBurst");
    try expectContains(errors, "_time:5m level:in(error) | stats by (service) count() as errors | filter errors:>=5\n");
    try expectContains(errors, "severity: 'warning'");
    const critical = try ruleBlock(first, "CriticalLogEvent");
    try expectContains(critical, "_time:1m level:in(critical,fatal) | stats by (service) count() as events | filter events:>=1\n");
    try expectContains(critical, "severity: 'critical'");
    try std.testing.expectEqual(@as(usize, 2), std.mem.count(u8, first, "source: 'victorialogs'"));
    try std.testing.expect(std.mem.indexOf(u8, first, "        for:") == null);
    for ([_][]const u8{ "_msg", "row_any", "request_id", "duration_ms", "{{ query" }) |sensitive| {
        try std.testing.expect(std.mem.indexOf(u8, first, sensitive) == null);
    }
    for ([_][]const u8{ errors, critical }) |block| {
        try expectContains(block, "{{ $labels.service }}");
        try expectContains(block, "{{ $value }}");
    }
}
