//! Two concrete evaluators: independent accounts, units and restart intentions.
const std = @import("std");
const remote = @import("../system/remote.zig");
const workflow = @import("install.zig");
const readiness = @import("readiness.zig");
const artifact = @import("../components/vmalert.zig");
const Arch = @import("../system/host.zig").Arch;
pub const Kind = enum { logs, metrics };

pub fn name(kind: Kind) []const u8 {
    return if (kind == .logs) "vmalert-logs" else "vmalert-metrics";
}
pub fn port(kind: Kind) u16 {
    return if (kind == .logs) 8880 else 8881;
}
pub fn marker(kind: Kind) []const u8 {
    return if (kind == .logs) artifact.pending else artifact.pending_metrics;
}
pub fn rulesPath(kind: Kind) []const u8 {
    return if (kind == .logs) "/etc/dragontools/vmalert-logs/rules.yml" else "/etc/dragontools/vmalert-metrics/rules.yml";
}
pub fn rules(a: std.mem.Allocator, kind: Kind) ![]const u8 {
    if (kind == .metrics) return @import("probes.zig").renderRules(a);
    const provisional = try @import("rules.zig").renderLogs(a);
    defer a.free(provisional);
    return std.mem.replaceOwned(u8, a, provisional, "# Generated by DragonTools; provisional local rules, not deployed.", "# Managed by DragonTools");
}
fn arguments(a: std.mem.Allocator, kind: Kind) ![]const u8 {
    // vmalert v1.152.0 divides by zero in Group.delayBeforeStart when this is 0s.
    // Keep the shared logs/metrics startup policy explicitly positive.
    return std.fmt.allocPrint(a, "-rule={s} -datasource.url=http://127.0.0.1:{d} -notifier.url=http://127.0.0.1:9093 -httpListenAddr=127.0.0.1:{d} -remoteWrite.url=http://127.0.0.1:8428 -remoteRead.url=http://127.0.0.1:8428 -group.maxStartDelay=1s", .{ rulesPath(kind), @as(u16, if (kind == .logs) 9428 else 8428), port(kind) });
}
pub fn unit(a: std.mem.Allocator, kind: Kind) ![]const u8 {
    const args = try arguments(a, kind);
    defer a.free(args);
    return std.fmt.allocPrint(a,
        \\# Managed by DragonTools
        \\[Unit]
        \\Description=DragonTools {s}
        \\After=network.target
        \\
        \\[Service]
        \\User=dt-{s}
        \\Group=dt-{s}
        \\ExecStart=/opt/dragontools/components/vmalert/current/vmalert-prod {s}
        \\Restart=on-failure
        \\RestartSec=5s
        \\TimeoutStopSec=60s
        \\NoNewPrivileges=yes
        \\PrivateTmp=yes
        \\PrivateDevices=yes
        \\ProtectHome=yes
        \\ProtectSystem=strict
        \\ProtectKernelTunables=yes
        \\ProtectKernelModules=yes
        \\ProtectControlGroups=yes
        \\RestrictSUIDSGID=yes
        \\LockPersonality=yes
        \\CapabilityBoundingSet=
        \\AmbientCapabilities=
        \\RestrictAddressFamilies=AF_INET AF_INET6 AF_UNIX
        \\ReadWritePaths=
        \\TasksMax=256
        \\UMask=0027
        \\LogRateLimitIntervalSec=30s
        \\LogRateLimitBurst=1000
        \\
        \\[Install]
        \\WantedBy=multi-user.target
        \\
    , .{ name(kind), name(kind), name(kind), args });
}

const preflight =
    \\id=$1; owner=dt-$id; home=/var/lib/dragontools/$id; config=/etc/dragontools/$id
    \\unit=/etc/systemd/system/dragontools-$id.service
    \\test -z "$(systemctl show -p DropInPaths --value "dragontools-$id.service")" || exit 42
    \\for path in "$unit" "$config/rules.yml" "/var/lib/dragontools/$id-restart-required"; do
    \\  test ! -L "$path" || exit 43
    \\  if test -e "$path"; then
    \\    test -f "$path" && test "$(stat -c '%h' "$path")" = 1 || exit 40
    \\    case "$path" in *restart-required) test "$(stat -c '%u:%g' "$path")" = 0:0 || exit 40;; *) grep -qx '# Managed by DragonTools' "$path" || exit 40;; esac
    \\  fi
    \\done
    \\for dir in /etc/dragontools "$config" "$home"; do
    \\  test ! -L "$dir" || exit 43
    \\  test ! -e "$dir" || test -d "$dir" || exit 40
    \\done
    \\if test -d "$config"; then
    \\  for path in "$config"/* "$config"/.[!.]* "$config"/..?*; do
    \\    if test ! -e "$path" && test ! -L "$path"; then continue; fi
    \\    case "$path" in
    \\      "$config/rules.yml") ;;
    \\      "$config/rules.yml".??????)
    \\        suffix=${path##*.}; case "$suffix" in *[!A-Za-z0-9]*) exit 40;; esac
    \\        test ! -L "$path" && test -f "$path" && test "$(stat -c '%u:%g:%h' "$path")" = 0:0:1 || exit 40;;
    \\      *) exit 40;;
    \\    esac
    \\  done
    \\fi
;
const account = preflight ++ "\n" ++
    \\if getent passwd "$owner" >/dev/null; then
    \\  test "$(getent passwd "$owner" | cut -d: -f7)" = /usr/sbin/nologin || exit 41
    \\  test "$(getent passwd "$owner" | cut -d: -f6)" = "$home" || exit 41
    \\  test "$(id -u "$owner")" -ne 0 && test "$(id -gn "$owner")" = "$owner" || exit 41
    \\  printf unchanged
    \\else
    \\  getent group "$owner" >/dev/null && exit 41
    \\  useradd --system --user-group --home-dir "$home" --no-create-home --shell /usr/sbin/nologin "$owner"
    \\  printf changed
    \\fi
;
const directories =
    \\id=$1; changed=0
    \\for dir in /etc/dragontools "/etc/dragontools/$id" "/var/lib/dragontools/$id"; do
    \\  owner=root:root; mode=755
    \\  case "$dir" in /var/lib/*) owner=dt-$id:dt-$id; mode=750;; esac
    \\  test ! -L "$dir" || exit 43
    \\  if test -e "$dir"; then
    \\    test -d "$dir" || exit 40
    \\    if test "$(stat -c '%U:%G' "$dir")" != "$owner"; then chown "$owner" "$dir"; changed=1; fi
    \\    if test "$(stat -c '%a' "$dir")" != "$mode"; then chmod "$mode" "$dir"; changed=1; fi
    \\  else mkdir "$dir"; chown "$owner" "$dir"; chmod "$mode" "$dir"; changed=1; fi
    \\done
    \\if test "$changed" = 1; then printf changed; else printf unchanged; fi
;
fn shell(a: std.mem.Allocator, kind: Kind, script: []const u8) ![]const u8 {
    return remote.shell(a, &.{ "sh", "-eu", "-c", script, "dragontools-vmalert", name(kind) });
}
pub fn install(a: std.mem.Allocator, r: remote.Remote, report: *workflow.Report, arch: Arch, kind: Kind) !void {
    _ = try report.call(r, .user, try shell(a, kind, account));
    _ = try report.call(r, .directories, try shell(a, kind, directories));
    _ = try report.call(r, .binary, try artifact.binaryCommand(a, arch));
    const content = try rules(a, kind);
    // Validate the fixed rule document using pinned vmalert before publication.
    const dry_run = try remote.shell(a, &.{
        "sh",                          "-eu",   "-c",
        \\if test -f "$2" && test ! -L "$2" && printf '%s' "$1" | cmp -s - "$2"; then exit 0; fi
        \\tmp=$(mktemp /tmp/dragontools-vmalert-rules.XXXXXX)
        \\trap 'rm -f "$tmp"' EXIT
        \\printf '%s' "$1" > "$tmp"
        \\/opt/dragontools/components/vmalert/current/vmalert-prod -dryRun "-rule=$tmp" >/dev/null 2>&1
        ,
        "dragontools-vmalert-dry-run", content, rulesPath(kind),
    });
    _ = try report.call(r, .config, dry_run);
    _ = try report.call(r, .config, try @import("../system/files.zig").writeCommand(a, rulesPath(kind), content, marker(kind)));
    _ = try report.call(r, .unit, try @import("../system/files.zig").writeCommand(a, try std.fmt.allocPrint(a, "/etc/systemd/system/dragontools-{s}.service", .{name(kind)}), try unit(a, kind), marker(kind)));
    _ = try report.call(r, .activate, if (kind == .logs) workflow.activation("vmalert-logs") else workflow.activation("vmalert-metrics"));
    try health(a, r, report, arch, kind);
    _ = try report.call(r, .finalize, try remote.shell(a, &.{ "rm", "-f", marker(kind) }));
}

const managed = preflight ++ "\n" ++
    \\expected=$2; unit_text=$3; rules=$4; version=$5
    \\check_property() { test "$(systemctl show -p "$1" --value "dragontools-$id.service")" = "$2"; }
    \\check_property FragmentPath "$unit"
    \\check_property LoadState loaded
    \\check_property UnitFileState enabled
    \\check_property NeedDaemonReload no
    \\check_property Environment ""
    \\check_property EnvironmentFiles ""
    \\check_property User "$owner"
    \\check_property Group "$owner"
    \\check_property ProtectSystem strict
    \\check_property ReadWritePaths ""
    \\check_property CapabilityBoundingSet ""
    \\check_property AmbientCapabilities ""
    \\families=$(systemctl show -p RestrictAddressFamilies --value "dragontools-$id.service")
    \\test "$(printf '%s\n' "$families" | tr ' ' '\n' | LC_ALL=C sort | tr '\n' ' ')" = 'AF_INET AF_INET6 AF_UNIX '
    \\for property in NoNewPrivileges PrivateTmp PrivateDevices ProtectHome ProtectKernelTunables ProtectKernelModules ProtectControlGroups RestrictSUIDSGID LockPersonality; do check_property "$property" yes; done
    \\for dir in /opt/dragontools /opt/dragontools/components /opt/dragontools/components/vmalert "/opt/dragontools/components/vmalert/$version" /etc/dragontools "$config" /var/lib/dragontools; do
    \\  test ! -L "$dir" && test -d "$dir" && test "$(stat -c '%u:%g:%a' "$dir")" = 0:0:755
    \\done
    \\test "$(stat -c '%U:%G:%a' "$home")" = "$owner:$owner:750"
    \\test "$(getent passwd "$owner" | cut -d: -f6-7)" = "$home:/usr/sbin/nologin"
    \\test "$(id -u "$owner")" -ne 0 && test "$(id -gn "$owner")" = "$owner"
    \\for file in "$unit" "$config/rules.yml"; do test "$(stat -c '%u:%g:%a' "$file")" = 0:0:644; done
    \\printf '%s' "$unit_text" | cmp -s - "$unit"
    \\printf '%s' "$rules" | cmp -s - "$config/rules.yml"
    \\test "$(readlink /opt/dragontools/components/vmalert/current)" = "$version"
    \\binary=/opt/dragontools/components/vmalert/$version/vmalert-prod
    \\test ! -L "$binary" && test -f "$binary" && test "$(stat -c '%u:%g:%a:%h' "$binary")" = 0:0:755:1
    \\printf '%s  %s\n' "$expected" "$binary" | sha256sum --check --status
;
pub const runtime =
    \\id=$1; expected=$2; args=$3; port=$4
    \\listeners=$(ss -H -ltnp "sport = :$port")
    \\if test -n "$listeners" && printf '%s\n' "$listeners" | grep -Ev "[[:space:]]127[.]0[.]0[.]1:$port[[:space:]]" >/dev/null; then exit 1; fi
    \\pid=$(systemctl show -p MainPID --value "dragontools-$id.service")
    \\case "$pid" in ''|*[!0-9]*) exit 1;; 0) exit 75;; esac
    \\test -d "/proc/$pid" || exit 75
    \\test "$(stat -c '%U:%G' "/proc/$pid")" = "dt-$id:dt-$id"
    \\actual=$(tr '\000' '\n' < "/proc/$pid/cmdline")
    \\test "$actual" = "$args"
    \\printf '%s  %s\n' "$expected" "/proc/$pid/exe" | sha256sum --check --status
    \\all_tcp=$(ss -H -ltnp)
    \\all_udp=$(ss -H -lunp)
    \\owned=$(printf '%s\n' "$all_tcp" | grep -F "pid=$pid," || :)
    \\if test -n "$owned" && printf '%s\n' "$owned" | grep -Ev "[[:space:]]127[.]0[.]0[.]1:$port[[:space:]]" >/dev/null; then exit 1; fi
    \\if printf '%s\n' "$all_udp" | grep -F "pid=$pid," >/dev/null; then exit 1; fi
    \\if test -n "$listeners"; then printf '%s\n' "$listeners" | grep -F "pid=$pid," >/dev/null || exit 1; fi
    \\systemctl is-active --quiet "dragontools-$id.service" || exit 75
;
fn runtimeCommand(a: std.mem.Allocator, arch: Arch, kind: Kind, tail: []const u8, check: readiness.Check) ![]const u8 {
    const args = try arguments(a, kind);
    const lines = try std.mem.replaceOwned(u8, a, args, " ", "\n");
    return remote.shell(a, &.{ "sh", "-eu", "-c", try std.fmt.allocPrint(a, "{s}\n{s}", .{ runtime, tail }), try std.fmt.allocPrint(a, "dragontools-{s}-{s}", .{ name(kind), @tagName(check) }), name(kind), artifact.artifact(arch).binary_sha256, try std.fmt.allocPrint(a, "/opt/dragontools/components/vmalert/current/vmalert-prod\n{s}", .{lines}), try std.fmt.allocPrint(a, "{d}", .{port(kind)}) });
}
pub fn health(a: std.mem.Allocator, r: remote.Remote, report: *workflow.Report, arch: Arch, kind: Kind) !void {
    _ = try readiness.deterministic(a, r, report, .managed_state, try remote.shell(a, &.{ "sh", "-eu", "-c", managed, "dragontools-vmalert-managed_state", name(kind), artifact.artifact(arch).binary_sha256, try unit(a, kind), try rules(a, kind), artifact.version }));
    try readiness.poll(a, r, report, .service_active, readiness.active_ms, try runtimeCommand(a, arch, kind, "true", .service_active), readiness.ready);
    try readiness.poll(a, r, report, .http_ready, readiness.http_ms, try runtimeCommand(a, arch, kind, "test -n \"$listeners\" || exit 75\ncurl --disable --noproxy '*' --fail --silent --max-time 5 \"http://127.0.0.1:$port/health\" >/dev/null || exit 75", .http_ready), readiness.ready);
    const helper = @embedFile("vmalert_rules.py");
    const query = try remote.shell(a, &.{ "python3", "-I", "-B", "-c", helper, @tagName(kind) });
    try readiness.poll(a, r, report, .rules_ready, readiness.telemetry_ms, try runtimeCommand(a, arch, kind, query, .rules_ready), readiness.ready);
}

test "vmalert instances have separate paths ports accounts and restart intentions" {
    const a = std.testing.allocator;
    for ([_]Kind{ .logs, .metrics }) |kind| {
        const text = try unit(a, kind);
        defer a.free(text);
        try std.testing.expect(std.mem.indexOf(u8, text, "ReadWritePaths=\n") != null);
        try std.testing.expect(std.mem.indexOf(u8, text, "-notifier.url=http://127.0.0.1:9093") != null);
        try std.testing.expect(std.mem.indexOf(u8, text, "0.0.0.0") == null);
        try std.testing.expect(std.mem.indexOf(u8, text, rulesPath(kind)) != null);
        const content = try rules(a, kind);
        defer a.free(content);
        try std.testing.expect(std.mem.startsWith(u8, content, "# Managed by DragonTools\n"));
        try std.testing.expect(std.mem.indexOf(u8, content, if (kind == .logs) "type: vlogs" else "for: 2m") != null);
    }
    try std.testing.expect(!std.mem.eql(u8, marker(.logs), marker(.metrics)));
    try std.testing.expect(port(.logs) != port(.metrics));
}

test "both vmalert units and runtime verification use the same positive startup delay" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const a = arena.allocator();
    for ([_]Kind{ .logs, .metrics }) |kind| {
        const text = try unit(a, kind);
        try std.testing.expectEqual(@as(usize, 1), std.mem.count(u8, text, "-group.maxStartDelay="));
        try std.testing.expect(std.mem.indexOf(u8, text, "-group.maxStartDelay=1s\n") != null);
        try std.testing.expect(std.mem.indexOf(u8, text, "-group.maxStartDelay=0s") == null);
        const verification = try runtimeCommand(a, .amd64, kind, "true", .service_active);
        try std.testing.expect(std.mem.indexOf(u8, verification, "-group.maxStartDelay=1s") != null);
        try std.testing.expect(std.mem.indexOf(u8, verification, "-group.maxStartDelay=0s") == null);
    }
}

test {
    _ = @import("vmalert_tests.zig");
}
